version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 200000000minion
  - 200000000stake
- name: bob
  coins:
  - 100000000minion
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5stake
  - 1000000000minion
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
